apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: coolapp2-rs
spec:
  replicas: 4 # 4 Pods should exist at all times.
  selector:  # Pods label should be defined in ReplicaSet label selector
    matchLabels:
      app: coolapp2
  template:
    metadata:
      name: coolapp2-pod
      labels:
        app: coolapp2 # Atleast 1 Pod label should match with ReplicaSet Label Selector
    spec:
      containers:
      - name: coolapp2
        image: stacksimplify/kubenginx:2.0.0
        ports:
          - containerPort: 80
