apiVersion: v1
kind: Service
metadata:
  name: coolapp2-pod-loadbalancer-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: coolapp2
  ports:
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port